name       : laz-perf
version    : 2.1.0
release    : 1
source     :
    - https://github.com/hobu/laz-perf/archive/refs/tags/2.1.0.tar.gz : 0812ee1fb34dbe245e89cf98cbd3ecec2f3e09db10bf679e6feb686e6908aa3d
license    : LGPL-2.1-or-later
component  : programming.library
summary    : Alternative LAZ implementation for C++
description: |
    LAZperf is an alternative LASzip implementation. LAZperf compresses LAS files into LAZ losslessly.
libsplit   : no
setup      : |
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
